### ISSUE TITLE
downloadable font: rejected by sanitizer

### ISSUE THREAD

**Issue by sea-kg** [ctfight/web#3]
downloadable font: rejected by sanitizer (font-family: "Avenir Next Cyr" style:normal weight:normal stretch:normal src index:0)
source: http://192.168.2.230:5000/fonts/AvenirNextCyr-Regular/AvenirNextCyr-Regular.eot

**Comment by Nitive** [comment]
Это нормально, подключаются шрифты разных форматов, с чем-то firefox может работать, с чем-то нет. Шрифты отображаются нормально.
