### ISSUE TITLE
text on index page

### ISSUE THREAD

**Issue by sea-kg** [ctfight/web#4]
Заменить текст:
"Здесь объясняется, что такое CTF и зачем нужен турнир. Душа моя озарена неземной радостью, как эти чудесные весенние утра, которыми я наслаждаюсь от всего сердца. Я совсем один и блаженствую в здешнем краю, словно созданном для таких, как я."
На:
"CTFight - это турнир по CTF. Тип игр attack-defence. Будет проведена серия игр. В каждой игре участвуют только две команды. Каждая игра длиться ровна 2 часа. Всего будет проведено 7 игр. Сервисы для игр пишут участники турнира - от каждой каманды по одному сервису и видео с разбором. Каждый сервис должен содержать минимум 2 уязвимости. Организаторы должны проверить сервис и если он подходит то команда принимается к участию в турнире. Подробнее можете прочитать на странице кодекса турнира."

**Comment by sea-kg** [comment]
Или "CTFight - это турнир по CTF. CTF - это соревнования по информационной бехопастности (или легальные хакерские игры). Турнир необходим как подготовка к большим игрищам."

**Comment by Nitive** [comment]
За этот текст отвечает переменная `what_is_ctfight` в файле [ru.yml](https://github.com/ctfight/web/blob/master/assets/yaml/ru.yml)
